# Generated by Django 4.1.4 on 2022-12-14 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_alter_movie_rating_alter_movie_user_movieorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='orders', through='movies.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg 13'), ('R', 'R'), ('NC-17', 'Nc 17')], default='G', max_length=20, null=True),
        ),
    ]
